### ISSUE TITLE
Добавить возможность установки фильтров

### ISSUE THREAD

**Issue by buzmakov** [ArtGrig/X-RAY-1#1]
Добавить возможность установки фильтров из меди и алюминия тольщиной от 0 до 1 мм с шагом 0.25 мм

Построить спектр рентгеновского источника ( на детекторе) в режиме Сu 40 кВ с фильтрами:
* Сu 0.2, 0.5 и 1 мм.
* Al 0.2, 0.5 и 1 мм. 
* и без них (на одном графике)

Результат сохранить в гитхаб в виде Ipython notebook с графиками.

Если есть вопросы, писать их как комментарии к этому тикету.

**Comment by ArtGrig** [comment]
Понял

7 июля 2016 г., 22:44 пользователь Alexey Buzmakov <notifications@github.com

**Comment by buzmakov** [comment]
Если сделал, пиши тут, что сделано.

**Comment by buzmakov** [comment]
По сути правильно,теперь чистим код:
 Заменяем функции absorb**1-4**(y, x) на absorb(y, x, filter_material, filter_thickness) + переименовать параметры y,x в понятные + добавить комментарии в питоновском стиле.  

Комментарии ко всем функциям добавляем -  а то код не читабельный.

**Comment by ArtGrig** [comment]
Все сделал.
